# Домашняя работа №5

In [2]:
import numpy as np

## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [8]:
N = 10
np.flip(np.arange(0, N))

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [10]:
def create_diag_matrix(n):
    return np.diag(np.arange(n - 1, -1, -1))
print('Task 2. Diag matrix:')
dm = create_diag_matrix(10)
print(dm)
print(f'Sum_of_diag_elems: {sum(dm.diagonal())}')

Task 2. Diag matrix:
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Sum_of_diag_elems: 45


## Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [11]:
left_side = np.array([
    [4, 2, 1],
    [1, 3, 0],
    [0, 5, 4]
])

right_side = np.array([4, 12, -3])
solution = linalg.solve(left_side, right_side)
x, y, z = solution

# Проверка решения
if not np.allclose(np.dot(left_side, solution), right_side):
    raise RuntimeError('Incorrect solution!')

print(f'ОТВЕТ: x = {x}, y = {y}, z = {z}')

ОТВЕТ: x = 0.4666666666666668, y = 3.844444444444444, z = -5.555555555555555
